### ISSUE TITLE
笔记02中 关于setState同步异步的问题

### ISSUE THREAD

**Issue by kiritoty** [dselegent/Learning-Notes#2]
笔记02中是这样写的

>React控制之外的事件中调用setState是同步更新的。比如原生js绑定的事件，setTimeout/setInterval等。

在最新的React 18.2版本中 即使是在setTimeout中调用setState 也是异步更新。  我测了一下React 17.  在17中setTimeout调用就是同步更新

**Comment by dselegent** [comment]
我去试试

**Comment by dselegent** [comment]
我在18版本中setTimeout测试发现也是异步的

**Comment by dselegent** [comment]
我在18版本中setTimeout测试发现也是异步的
